.Dd August 2nd, 2017    
.Dt HIBISCUS 
.Os
.Sh NAME
.Nm Hibiscus - Hibiscus syriacus
.Os
.Sh FAMILY
Malvaceae
.Os 
.Sh TYPE
Flowering
.Sh QUALITIES
.Os
.Sh Medicinal
.Os
Anthelmintic; Antiphlogistic; Antipruritic; Demulcent; Diuretic; Emollient; Expectorant; Febrifuge; Ophthalmic; Skin; Stomachic; Styptic.
.Os
.Sh Edibility
.Os
Edible Parts: Flowers; Leaves; Oil; Root. 
Edible Uses: Oil; Tea.
.Os
Young leaves - raw or cooked[2, 177, 179, 183]. A very mild flavour, though slightly on the tough side, they make an acceptable addition to the salad bowl[K]. A tea is made from the leaves[2, 177, 240] or the flowers[183]. Flowers - raw or cooked[74, 105, 183]. A mild flavour and mucilaginous texture, they are delightful in salads, both for looking at and for eating[K]. Root - it is edible but very fibrousy[144]. Mucilaginous, without very much flavour[144].
.Os
.Sh Warnings
None immediate.
.Sh PFAF ENTRY
The leaves are diuretic, expectorant and stomachic[218, 240]. A decoction of the flowers is diuretic, ophthalmic and stomachic[147, 178, 218]. It is also used in the treatment of itch and other skin diseases[240], dizziness and bloody stools accompanied by much gas[147]. The bark contains several medically active constituents, including mucilage, carotenoids, sesquiterpenes and anthocyanidins[279]. A decoction of the root bark is antiphlogistic, demulcent, emollient, febrifuge, haemostatic and vermifuge[218, 240]. It is used in the treatment of diarrhoea, dysentery, abdominal pain, leucorrhoea, dysmenorrhoea[240, 279] and dermaphytosis[147].
.Sh WILDCRAFTING HABITAT
Yes; found in New York State. Please edit according to location.
.Sh ADDITIONAL NOTES
Hibiscus is also a particularly good anti-inflammatory for mucus membranes, and is recommended as an addition for any cold or flu remedy.
.Sh Specific Reference
None
.Sh AUTHORS
A group of individuals calling themselves Tech Autonomists.
